FROM debian@sha256:52af198afd8c264f1035206ca66a5c48e602afb32dc912ebf9e9478134601ec4

############
# ENV VARS #
############
ENV DEBIAN_FRONTEND noninteractive
ENV SHELL /bin/bash
ENV NON_PRIVILEGED_USER="jovyan"
ENV NON_PRIVILEGED_USER_PASSWORD="pass"
ENV NON_PRIVILEGED_USER_GROUP="app"
ENV CONDA_DIR /home/$NON_PRIVILEGED_USER/anaconda
ENV NVM_DIR /usr/local/nvm
ENV NVM_INSTALLER_FILE "install-nvm.sh"
ENV NODE_VERSION v8.0.0

#################
# ADDING A USER #
#################
# For more info please check useradd --help or man useradd.
RUN groupadd -r $NON_PRIVILEGED_USER_GROUP -g 1000 \
 && useradd \
    --uid 1000 \
    --system \
    --gid $NON_PRIVILEGED_USER_GROUP \
    --create-home \
    --home-dir /home/$NON_PRIVILEGED_USER/ \
    --shell /bin/bash \
    --comment "non-privileged user" \
    $NON_PRIVILEGED_USER \
 && chmod 755 /home/$NON_PRIVILEGED_USER/ \
 && echo "$NON_PRIVILEGED_USER:$NON_PRIVILEGED_USER_PASSWORD" | chpasswd

USER root

RUN mkdir -p /home/jovyan/util/superhero-datascience
COPY /theme-superhero-datascience/ /home/jovyan/util/theme-superhero-datascience
RUN chown -R jovyan /home/jovyan
RUN chgrp -R users /home/jovyan
RUN chmod -R 777 /home/jovyan/util

USER jovyan



RUN conda install -c conda-forge --yes --quiet \
    'nodejs<10' \
    notebook \
    jupyter \
    jupyterlab

RUN cd /home/jovyan/util/theme-superhero-datascience \
 && rm -rf node_modules \
 && npm install webpack -g \
 && npm install && npm run build \
 && jupyter lab clean \
 && jupyter labextension install \
 && jupyter lab build

CMD jupyter lab

